#include <stdio.h>
#include <windows.h>
#include "vardeclare.h"
#include "menu.h"
#include "newacc.h"
#include "edit.h"
#include "transaction.h"
#include "see.h"
#include "erase.h"
#include "view.h"
#include "delay.h"
#include "close.h"